// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfkc8qWQu6k1h-c-dPa8ASerh2KhW8JQ8',
    appId: '1:378719678991:web:d1c79191187ebdff62e97a',
    messagingSenderId: '378719678991',
    projectId: 'zoom-clone-5b832',
    authDomain: 'zoom-clone-5b832.firebaseapp.com',
    storageBucket: 'zoom-clone-5b832.appspot.com',
    measurementId: 'G-LG4V1ZQ14M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFV7aNR1jmncNmgsR1ItjVS13WpUEGPYU',
    appId: '1:378719678991:android:309e7275f725d2b862e97a',
    messagingSenderId: '378719678991',
    projectId: 'zoom-clone-5b832',
    storageBucket: 'zoom-clone-5b832.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTMjPMiJiGWhiSPRgbQ1PZqm-j5y8aBxs',
    appId: '1:378719678991:ios:de68fae0f86aa89462e97a',
    messagingSenderId: '378719678991',
    projectId: 'zoom-clone-5b832',
    storageBucket: 'zoom-clone-5b832.appspot.com',
    iosClientId: '378719678991-lsbrvltcelbtge8c1qcgopmhhqr202h9.apps.googleusercontent.com',
    iosBundleId: 'com.example.zoomClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTMjPMiJiGWhiSPRgbQ1PZqm-j5y8aBxs',
    appId: '1:378719678991:ios:bba58b1e5addb59d62e97a',
    messagingSenderId: '378719678991',
    projectId: 'zoom-clone-5b832',
    storageBucket: 'zoom-clone-5b832.appspot.com',
    iosClientId: '378719678991-mmqiubfn7p49mlo7frfb88sodqr275c8.apps.googleusercontent.com',
    iosBundleId: 'com.example.zoomClone.RunnerTests',
  );
}
