# Generated by Django 5.0.6 on 2024-10-26 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('weight', models.IntegerField()),
            ],
        ),
    ]
